---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sinergia/public_html/
    - /usr/bin/rsync -a --delete --exclude='.git/' --exclude='.github/' --exclude='.cpanel.yml' --exclude='.gitignore' --exclude='README.md' --exclude='php.ini' --exclude='cgi-bin/' ./ "$DEPLOYPATH"
