---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sinergia/public_html/
    - /bin/rm -rf "${DEPLOYPATH}assets" "${DEPLOYPATH}css" "${DEPLOYPATH}js"
    - /bin/rm -f "${DEPLOYPATH}"*.html
    - /bin/cp -a assets css js "$DEPLOYPATH"
    - /bin/cp -a ./*.html "$DEPLOYPATH"
